# 基础配置
use_default_settings:
  engines:
    keep_only:
      - baidu
      - bing

# 服务器设置
server:
  secret_key: '779c5b69fe650f147be9012abca6b44a8697acdb2817b46353f4779bb07d81d1'
  base_url: /

# 搜索设置
search:
  safe_search: 0
  default_lang: 'auto'
  # 开启 json 输出，这是 lobe 调用所必需的
  formats:
    - html
    - json
  # 分类标签配置
  categories_as_tabs:
    general:
    images:
    videos:
    news:
    map:
    music:
    it:
    science:
    files:
    social media:

# 禁用机器人检测
botdetection:
  enabled: false

# 配置引擎
engines:
  # 启用百度和必应引擎
  - name: baidu
    disabled: false
  - name: bing
    disabled: false